config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    mount DelayedJobWeb, at: '/delayed_job'
  end

  get 'pages/contact', to: 'pages#contact', as: 'contact'

  get 'pages/copyright_and_permissions', to: 'pages#copyright_and_permissions', as: 'copyright_and_permissions'

  get 'pages/interview_guidelines', to: 'pages#interview_guidelines', as: 'interview_guidelines'

  get 'pages/family_history', to: 'pages#family_history', as: 'family_history'

  get 'pages/programs', to: 'pages#programs', as: 'programs'

  get 'pages/organizations', to: 'pages#organizations', as: 'organizations'

  get 'pages/training', to: 'pages#training', as: 'training'

  get 'pages/bibliography', to: 'pages#bibliography', as: 'bibliography'

  get '/admin', to: 'admin#index', as: 'admin'
  get '/admin/importer_log', to: 'admin#importer_log'
  get '/admin/worker_log', to: 'admin#worker_log'
  get '/admin/development_log', to: 'admin#development_log'
  get '/admin/download_all_logs', to: 'admin#download_all_logs'
  post '/admin/clear_all_logs', to: 'admin#clear_all_logs'
  get 'admin/importer_running', to: 'admin#importer_running'
  get 'admin/single_import_progress', to: 'admin#single_import_progress'
  get 'admin/full_import_progress/:job_id', to: 'admin#full_import_progress', as: 'full_import_progress'
  get 'admin/full_import_progress', to: 'admin#latest_full_import_progress'
  get 'admin/single_import_progress/:id', to: 'admin#single_import_progress'
  post 'admin/run_full_import', to: 'admin#run_full_import', as: 'run_full_import'
  post 'admin/run_single_import', to: 'admin#run_single_import', as: 'run_single_import'
  delete 'admin/delete_jobs', to: 'admin#delete_jobs', as: 'delete_jobs'

  delete 'destroy_all_delayed_jobs', to: 'admin#destroy_all_delayed_jobs'

  mount Blacklight::Engine => '/'
  mount BlacklightDynamicSitemap::Engine => '/'


  root to: "catalog#index"
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :interviewee, only: [:index], as: 'interviewee', path: '/interviewee', controller: 'interviewee' do
    concerns :searchable
  end

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  resource :full_text, only: [:index], as: 'full_text', path: '/full_text', controller: 'full_text' do
    concerns :searchable
  end

  devise_for :users
  concern :exportable, Blacklight::Routes::Exportable.new
  concern :marc_viewable, Blacklight::Marc::Routes::MarcViewable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns [:exportable, :marc_viewable]
  end

  resource :bookmarks, only: [:index], as: 'bookmarks', path: '/bookmarks', controller: 'bookmarks' do
    concerns :searchable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/index.html.erb
<div class="container import">
  <div class="u-heading-v2-5--bottom g-brd-primary">
    <h2 class="u-heading-v2__title text-uppercase g-font-weight-300 mb-0 g-mt-40">Manage Library</h2>
  </div>

  <h4 class="g-mt-40 g-mb-40">Manually trigger records importer</h4>

  <div class="d-flex gap-3 flex-wrap g-mt-40 g-mb-40">
    <div>
      <%= form_tag run_single_import_url, method: :post, id: "run-single-import-button", class: "btn btn-lg btn-primary", local: false do %>
        <div class="form-group">
          <%= text_field_tag 'id', '', class: 'form-control', placeholder: 'Enter ID' %>
        </div>
        <%= button_tag 'Run Single Import', class: 'btn btn-lg btn-primary', type: 'submit' %>
      <% end %>
    </div>

    <div class="align-self-end">
      <%= form_with url: run_full_import_url, method: :post, id: "run-full-import-form", local: false do %>
        <%= button_tag 'Run Full Import', class: 'btn btn-lg btn-primary', type: 'submit' %>

        <div class="form-check mt-3 d-flex align-items-center gap-2">
          <%= check_box_tag :delete, true, false, class: 'form-check-input', id: 'delete-checkbox' %>
          <%= label_tag :delete, 'With Fresh Index', class: 'form-check-label mb-0' %>
          <span class="font-awesome-question-circle series-tooltip">
            <span class="series-tooltip-text">
              If checked, this clears all previously indexed Solr records before starting a fresh full import.
            </span>
          </span>
        </div>
      <% end %>
    </div>
  </div>

  <div class="g-mt-20 g-mb-20 well" style="display: none">
    <div class="sr-only progress-status text-primary"></div>
    <h4 class="g-mt-40 g-mb-40">Import Progress</h4>
    <div class="progress" style="height: 20px;">
      <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar">0%</div>
    </div>
  </div>

  <div id="import-notice" class="alert" style="display: none; margin-bottom: 10px;"></div>
  <div id="flashes"></div>

  <h4 class="g-mt-40 g-mb-40">Background Jobs</h4>

  <div class="d-flex gap-3 flex-wrap my-4">
    <%= link_to delayed_job_web_path, class: "btn btn-lg btn-primary", target: "_blank" do %>
      <i class="fa fa-tachometer"></i> Jobs Dashboard
    <% end %>

    <%= button_to destroy_all_delayed_jobs_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-lg btn-danger' do %>
      <i class="fa fa-trash"></i> Delete All Jobs
    <% end %>
  </div>

  <h4 class="g-mt-40 g-mb-40">Logs</h4>

  <div class="card g-mt-20 g-mb-20">
    <div class="card-body">
      <div class="d-flex justify-content-between align-items-center mb-2">
        <ul class="nav nav-tabs nav-justified full-width-tab-mobile custom-tabs mb-0" id="logTabs" role="tablist">
          <li class="nav-item">
            <a class="nav-link active hero-links u-link-v5 g-color-main g-color-primary--hover g-font-size-20"
              id="development-tab"
              data-bs-toggle="tab"
              href="#development-log"
              role="tab"
              aria-controls="development-log"
              aria-selected="true">
              Development Log
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link hero-links u-link-v5 g-color-main g-color-primary--hover g-font-size-20"
              id="worker-tab"
              data-bs-toggle="tab"
              href="#worker-log"
              role="tab"
              aria-controls="worker-log"
              aria-selected="false">
              Worker Log
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link hero-links u-link-v5 g-color-main g-color-primary--hover g-font-size-20"
              id="importer-tab"
              data-bs-toggle="tab"
              href="#importer-log"
              role="tab"
              aria-controls="importer-log"
              aria-selected="false">
              Importer Log
            </a>
          </li>
        </ul>
        <%= button_to "/admin/clear_all_logs", method: :post, class: "btn btn-lg btn-warning ms-3", data: { confirm: 'Are you sure you want to clear all logs?' } do %>
          <i class="fa fa-trash"></i> Clear All Logs
        <% end %>
      </div>

    </div>

    <div class="tab-content" id="logTabsContent" style="border: 1px solid #ddd; padding: 10px; height: 350px; overflow-y: scroll; font-family: monospace; font-size: 14px; background: #f8f9fa;">

      <div class="tab-pane fade show active position-relative" id="development-log" role="tabpanel" aria-labelledby="development-tab">
        <div id="development-log-content">Loading Development log...</div>

        <div class="text-end g-mt-10">
          <% if Rails.env.development? %>
            <%= link_to "/admin/development_log", class: "btn btn-success btn-sm", download: true do %>
              <i class="fa fa-download"></i> Download
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="tab-pane fade position-relative" id="worker-log" role="tabpanel" aria-labelledby="worker-tab">
        <div id="worker-log-content">Loading Worker log...</div>

        <div class="text-end g-mt-10">
          <%= link_to "/admin/worker_log", class: "btn btn-success btn-sm", download: true do %>
            <i class="fa fa-download"></i> Download
          <% end %>
        </div>
      </div>

      <div class="tab-pane fade position-relative" id="importer-log" role="tabpanel" aria-labelledby="importer-tab">
        <div id="importer-log-content">Loading Importer log...</div>

        <div class="text-end g-mt-10">
          <%= link_to "/admin/importer_log", class: "btn btn-success btn-sm", download: true do %>
            <i class="fa fa-download"></i> Download
          <% end %>
        </div>
      </div>

    </div>
    <%= link_to "/admin/download_all_logs", class: "btn btn-lg btn-success mt-3", download: true do %>
      <i class="fa fa-download"></i> Download All Logs
    <% end %>
  </div>

  <div class="g-mt-40 g-mb-40">
    <%= link_to t('blacklight.header_links.logout'), destroy_user_session_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>