config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    mount DelayedJobWeb, at: '/delayed_job'
  end

  get 'pages/contact', to: 'pages#contact', as: 'contact'

  get 'pages/copyright_and_permissions', to: 'pages#copyright_and_permissions', as: 'copyright_and_permissions'

  get 'pages/interview_guidelines', to: 'pages#interview_guidelines', as: 'interview_guidelines'

  get 'pages/family_history', to: 'pages#family_history', as: 'family_history'

  get 'pages/programs', to: 'pages#programs', as: 'programs'

  get 'pages/organizations', to: 'pages#organizations', as: 'organizations'

  get 'pages/training', to: 'pages#training', as: 'training'

  get 'pages/bibliography', to: 'pages#bibliography', as: 'bibliography'

  get '/admin', to: 'admin#index', as: 'admin'
  get '/admin/importer_log', to: 'admin#importer_log'
  get '/admin/worker_log', to: 'admin#worker_log'
  get '/admin/development_log', to: 'admin#development_log'
  get '/admin/download_all_logs', to: 'admin#download_all_logs'
  post '/admin/clear_all_logs', to: 'admin#clear_all_logs'
  get 'admin/importer_running', to: 'admin#importer_running'
  get 'admin/single_import_progress', to: 'admin#single_import_progress'
  get 'admin/full_import_progress/:job_id', to: 'admin#full_import_progress', as: 'full_import_progress'
  get 'admin/full_import_progress', to: 'admin#latest_full_import_progress'
  get 'admin/single_import_progress/:id', to: 'admin#single_import_progress'
  post 'admin/run_full_import', to: 'admin#run_full_import', as: 'run_full_import'
  post 'admin/run_single_import', to: 'admin#run_single_import', as: 'run_single_import'
  delete 'admin/delete_jobs', to: 'admin#delete_jobs', as: 'delete_jobs'

  delete 'destroy_all_delayed_jobs', to: 'admin#destroy_all_delayed_jobs'

  mount Blacklight::Engine => '/'
  mount BlacklightDynamicSitemap::Engine => '/'


  root to: "catalog#index"
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :interviewee, only: [:index], as: 'interviewee', path: '/interviewee', controller: 'interviewee' do
    concerns :searchable
  end

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  resource :full_text, only: [:index], as: 'full_text', path: '/full_text', controller: 'full_text' do
    concerns :searchable
  end

  devise_for :users
  concern :exportable, Blacklight::Routes::Exportable.new
  concern :marc_viewable, Blacklight::Marc::Routes::MarcViewable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns [:exportable, :marc_viewable]
  end

  resource :bookmarks, only: [:index], as: 'bookmarks', path: '/bookmarks', controller: 'bookmarks' do
    concerns :searchable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<!-- Copyright Footer -->
<footer>
  <div class="footer-row row g-bg-gray g-py-20">
    <div class="container">
      <div class="col-md-8 border-end float-start">
        <%= image_tag("footer_logo.svg", alt: "UCLA Library Logo", class: 'footer-logo') %>
        <p class="g-mt-40"> The UCLA Library creates a vibrant nexus of ideas, collections, expertise, and spaces in which users illuminate solutions for local and global challenges. We constantly evolve to advance UCLA’s research, education, and public service mission by empowering and inspiring communities of scholars and learners to discover, access, create, share, and preserve knowledge.</p>
      </div>

      <div class="row col-md-2 padding-top border-start float-start">
        <ul class="list-unstyled">
          <li><a class="footer-link" href="http://www.library.ucla.edu/about">About the UCLA Library</a></li>

          <li><a class="footer-link" href="http://www.library.ucla.edu/about/about-collections">About the Collections</a></li>

          <li><a class="footer-link" href="https://www.library.ucla.edu/about/giving-library">Giving to UCLA Library</a></li>
        </ul>
      </div>
      <div class="row col-md-2 padding-top border-start float-start">
        <ul class="list-unstyled">
          <li><a class="footer-link" href="http://www.ucla.edu/">UCLA Homepage</a></li>
          <li><a class="footer-link" href="http://www.library.ucla.edu/about/jobs-ucla-library">Jobs @ UCLA Library</a></li>
          <li><a class="footer-link" href="http://www.library.ucla.edu/about/social-media-directory">Social Media Directory</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="g-bg-blue g-color-white-opacity-0_8 g-py-20">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center text-md-start g-mb-10 g-mb-0--md">
          <small class="text-center d-block g-font-size-default g-mr-10 g-mb-10 g-mb-0--md">© <%= Time.now.year %> UCLA Library | Center for Oral History Research | <%= link_to 'Admin', admin_path, class: 'admin-footer-link' %></small>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- End Copyright Footer -->

app/views/shared/_ie_message.html.erb
<% # CUSTOM: Adds ie error message per client needs %>
<div class="row show-for-ie">
  <div class="col-md-12">
    <!-- Warning Alert -->
    <div class="alert alert-info ie-alert show" role="alert">
      
      <h4 class="h5">
        <i class="fa fa-exclamation-triangle"></i>
        Warning!
      </h4>
      This site is not optimized for Internet Explorer. Audio players and some other items will not function.
    </div>
    <!-- End Warning Alert -->
  </div>
</div>

app/views/shared/_multiple.html.erb
<% # CUSTOM: Custom themeing %>
<% value.each do |v| %>
  <div class='multiple-line-result'>
    <%= v %>
  </div>
<% end %>

app/views/shared/_user_util_links.html.erb
<div class="navbar-right">
<ul class="navbar-nav">
  <li class="nav-item active dropdown">

    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownInfoLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Info
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownInfoLink">
      <li class="dropdown-item"><%= link_to 'Contact', contact_path, class: 'dropdown-link' %></li>
      <li class="dropdown-item"><%= link_to 'Admin', admin_path, class: 'dropdown-link' %></li>
    </ul>
  </li>

  <li class="nav-item active dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownCollectionsLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Collections
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownCollectionsLink">
      <li class="dropdown-item"><%= link_to "Browse by Interviewees", search_interviewee_path, class: 'dropdown-link' %></li>
      <li class="dropdown-item"><%= link_to "Browse by Topics", '/#collections', class: 'dropdown-link' %></li>
    </ul>
  </li>

  <li class="nav-item active dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownRightsLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Rights
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownRightsLink">
      <li class="dropdown-item"><%= link_to 'Copyright and Permissions', copyright_and_permissions_path, class: 'dropdown-link' %></li>
    </ul>
  </li>
  <li class="nav-item active dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownResourcesLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Resources
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownResourcesLink">
      <li class="dropdown-item"><%= link_to 'Interviewing Guidelines', asset_path("Interviewing_Guidelines.pdf", class: 'dropdown-link') %></li>
      <li class="dropdown-item"><%= link_to 'Sample Legal Agreement', asset_path("SampleLegalAgreement.pdf", class: 'dropdown-link') %></li>
      <li class="dropdown-item"><%= link_to 'Family History Sample Outline', asset_path("Family_History_Sample_Outline.pdf", class: 'dropdown-link') %></li>
      <li class="dropdown-item"><%= link_to 'Selected Oral History Organizations', organizations_path, class: 'dropdown-link' %></li>
      <li class="dropdown-item"><%= link_to 'Oral History Training', training_path, class: 'dropdown-link' %></li>
    </ul>
  </li>

  <%= render_nav_actions do |config, action|%>
    <li class="nav-item active"><%= action %></li>
  <% end %>

</ul>

<!-- REMOVE LOGIN FROM NAVBAR
<#% if has_user_authentication_provider? %>
  <ul class="nav navbar-nav">
    <#% if current_user %>
    <li>
      <<li class="dropdown-item">#%= link_to t('blacklight.header_links.logout'), destroy_user_session_path %></li>
    </li>
    <#% unless current_user.to_s.blank? -%>
    <li>
      <<li class="dropdown-item">#%= link_to current_user, edit_user_registration_path %></li>
    </li>
    <#% end %>
    <#% else %>
    <li>
      <<li class="dropdown-item">#%= link_to t('blacklight.header_links.login'), new_user_session_path %></li>
    </li>
    <#% end %>
    </ul>
<#% end %>-->
</div>