config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    mount DelayedJobWeb, at: '/delayed_job'
  end

  get 'pages/contact', to: 'pages#contact', as: 'contact'

  get 'pages/copyright_and_permissions', to: 'pages#copyright_and_permissions', as: 'copyright_and_permissions'

  get 'pages/interview_guidelines', to: 'pages#interview_guidelines', as: 'interview_guidelines'

  get 'pages/family_history', to: 'pages#family_history', as: 'family_history'

  get 'pages/programs', to: 'pages#programs', as: 'programs'

  get 'pages/organizations', to: 'pages#organizations', as: 'organizations'

  get 'pages/training', to: 'pages#training', as: 'training'

  get 'pages/bibliography', to: 'pages#bibliography', as: 'bibliography'

  get '/admin', to: 'admin#index', as: 'admin'
  get '/admin/importer_log', to: 'admin#importer_log'
  get '/admin/worker_log', to: 'admin#worker_log'
  get '/admin/development_log', to: 'admin#development_log'
  get '/admin/download_all_logs', to: 'admin#download_all_logs'
  post '/admin/clear_all_logs', to: 'admin#clear_all_logs'
  get 'admin/importer_running', to: 'admin#importer_running'
  get 'admin/single_import_progress', to: 'admin#single_import_progress'
  get 'admin/full_import_progress/:job_id', to: 'admin#full_import_progress', as: 'full_import_progress'
  get 'admin/full_import_progress', to: 'admin#latest_full_import_progress'
  get 'admin/single_import_progress/:id', to: 'admin#single_import_progress'
  post 'admin/run_full_import', to: 'admin#run_full_import', as: 'run_full_import'
  post 'admin/run_single_import', to: 'admin#run_single_import', as: 'run_single_import'
  delete 'admin/delete_jobs', to: 'admin#delete_jobs', as: 'delete_jobs'

  delete 'destroy_all_delayed_jobs', to: 'admin#destroy_all_delayed_jobs'

  mount Blacklight::Engine => '/'
  mount BlacklightDynamicSitemap::Engine => '/'


  root to: "catalog#index"
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :interviewee, only: [:index], as: 'interviewee', path: '/interviewee', controller: 'interviewee' do
    concerns :searchable
  end

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  resource :full_text, only: [:index], as: 'full_text', path: '/full_text', controller: 'full_text' do
    concerns :searchable
  end

  devise_for :users
  concern :exportable, Blacklight::Routes::Exportable.new
  concern :marc_viewable, Blacklight::Marc::Routes::MarcViewable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns [:exportable, :marc_viewable]
  end

  resource :bookmarks, only: [:index], as: 'bookmarks', path: '/bookmarks', controller: 'bookmarks' do
    concerns :searchable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/catalog_controller.rb
# frozen_string_literal: true
class CatalogController < ApplicationController

  include Blacklight::Catalog
  include Blacklight::Marc::Catalog
  include Blacklight::DefaultComponentConfiguration
  before_action :setup_negative_captcha, only: [:email]

  configure_blacklight do |config|
    config.full_width_layout = true
    ## Class for sending and receiving requests from a search index
    # config.repository_class = Blacklight::Solr::Repository
    #
    ## Class for converting Blacklight's url parameters to into request parameters for the search index
    # config.search_builder_class = ::SearchBuilder
    #
    ## Model that maps search index responses to the blacklight response model
    # config.response_model = Blacklight::Solr::Response

    ## Default parameters to send to solr for all search-like requests. See also SearchBuilder#processed_parameters
    config.default_solr_params = {
      rows: 10,
      :"hl" => true,
      :"hl.fl" => "abstract_t, biographical_t, subject_t, description_t, audio_b, extent_t, language_t, author_t, interviewee_t, title_t, subtitle_t, series_t",
      :"hl.simple.pre" => "<span class='label label-warning'>",
      :"hl.simple.post" => "</span>",
      :"hl.fragsize" => 100,#The fragsize is set to 100 so when the index_filter method is run on the abstract_t and description_t and they have search terms within that will be highlighted, it only considers 100 fragzise limit. We then use .truncate at 150 characters allowing the hl.simple.pre and hl.simple.post to insert less than the remaining 50 characters differance between 100 fragsize and 150 chars till truncate so that the classes added on hl.simple.pre and hl.simple.post will not get truncated.
    }
    # The fragsize is set to 100 so when the index_filter method is run on the abstract_t and
    # description_t and they have search terms within that will be highlighted, it only considers 100 fragzise limit.
    # We then use .truncate at 150 characters allowing the hl.simple.pre and hl.simple.post to insert less than the r
    # emaining 50 characters differance between 100 fragsize and 150 chars till truncate so that the classes added on
    # hl.simple.pre and hl.simple.post will not get truncated.

    # solr path which will be added to solr base url before the other solr params.
    #config.solr_path = 'select'

    # items to show per page, each number in the array represent another option to choose from.
    #config.per_page = [10,20,50,100]

    ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SearchHelper#solr_doc_params) or
    ## parameters included in the Blacklight-jetty document requestHandler.
    #
    config.default_document_solr_params = {
     #  qt: 'document',
     ## These are hard-coded in the blacklight 'document' requestHandler
     # fl: '*',
     # rows: 1,
     # q: '{!term f=id v=$id}'
      :"hl" => true,
      :"hl.fragsize" => 0,
      :"hl.preserveMulti" => true,
      :"hl.fl" => "biographical_t, subject_t, description_t, person_present_t, place_t, supporting_documents_t, interviewer_history_t, process_interview_t, audio_b, extent_t, rights_t, language_t, author_t, interviewee_t, title_t, subtitle_t, series_t, links_t, abstract_t admin_note_t",
      :"hl.simple.pre" => "<span class='label label-warning'>",
      :"hl.simple.post" => "</span>",
      :"hl.alternateField" => "dd"
    }

    # solr field configuration for search results/index views
    config.index.title_field = 'title_display'
    config.index.display_type_field = 'format'
    #config.index.thumbnail_field = 'thumbnail_path_ss'
    config.index.document_actions.delete(:bookmark)
    config.show.document_actions.delete(:bookmark)
    config.add_nav_action(:bookmark, partial: 'blacklight/nav/bookmark', if: :render_bookmarks_control?)
    config.add_nav_action(:search_history, partial: 'blacklight/nav/search_history')
    config.add_show_tools_partial(:bookmark, component: Blacklight::Document::BookmarkComponent, if: :render_bookmarks_control?)
    config.add_results_document_tool(:bookmark, component: Blacklight::Document::BookmarkComponent, if: :render_bookmarks_control?)


    config.add_results_document_tool(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)

    config.add_results_collection_tool(:sort_widget)
    config.add_results_collection_tool(:per_page_widget)
    config.add_results_collection_tool(:view_type_group)

    config.add_show_tools_partial(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)
    config.add_show_tools_partial(:email, callback: :email_action, validator: :validate_email_params)
    config.add_show_tools_partial(:sms, if: :render_sms_action?, callback: :sms_action, validator: :validate_sms_params)
    config.add_show_tools_partial(:citation)

    # solr field configuration for document/show views
    #config.show.title_field = 'title_display'
    #config.show.display_type_field = 'format'
    #config.show.thumbnail_field = 'thumbnail_path_ss'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    #
    # set :index_range to true if you want the facet pagination view to have facet prefix-based navigation
    #  (useful when user clicks "more" on a large facet and wants to navigate alphabetically across a large set of results)
    # :index_range can be an array or range of prefixes that will be used to create the navigation (note: It is case sensitive when searching values)

    #config.add_facet_field 'format', label: 'Format'
#    config.add_facet_field 'pub_date', label: 'Publication Year', single: true
    config.add_facet_field 'subject_topic_facet', label: 'Topic', limit: 20, index_range: 'A'..'Z'
    config.add_facet_field 'language_facet', label: 'Language', limit: true
    #config.add_facet_field 'lc_1letter_facet', label: 'Call Number'
    #config.add_facet_field 'subject_geo_facet', label: 'Region'
#    config.add_facet_field 'subject_era_facet', label: 'Era'
    config.add_facet_field 'series_facet', label: 'Series'
    #config.add_facet_field 'type_of_resource_facet', label: 'Type of Resource'
    config.add_facet_field 'audio_b', label: 'Has Media', helper_method: 'audio_icon_with_text'
    #config.add_facet_field 'example_pivot_field', label: 'Pivot Field', :pivot => ['format', 'language_facet']

#    config.add_facet_field 'example_query_facet_field', label: 'Publish Date', :query => {
#       :years_5 => { label: 'within 5 Years', fq: "pub_date:[#{Time.zone.now.year - 5 } TO *]" },
#       :years_10 => { label: 'within 10 Years', fq: "pub_date:[#{Time.zone.now.year - 10 } TO *]" },
#       :years_25 => { label: 'within 25 Years', fq: "pub_date:[#{Time.zone.now.year - 25 } TO *]" }
#    }


    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results and bookmarks) view
    #   The ordering of the field names is the order of the display
    # config.add_index_field 'subtitle_display', label: 'Subtitle'
    config.add_index_field 'subject_t', label: 'Topic', helper_method: :split_multiple, highlight: true, solr_params: { :"hl.alternateField" => "dd" }
    config.add_index_field 'extent_t', label: 'Length', highlight: true, solr_params: { :"hl.alternateField" => "dd" }
    config.add_index_field 'language_t', label: 'Language', highlight: true, solr_params: { :"hl.alternateField" => "dd" }
    config.add_index_field 'audio_b', label: 'Audio', highlight: true, solr_params: { :"hl.alternateField" => "dd" }, helper_method: 'audio_icon'
    config.add_index_field 'abstract_t', label: 'Series Statement', highlight: true, solr_params: { :"hl.alternateField" => "dd", :"hl.maxAlternateFieldLength" => 0, :"hl.highlightAlternate" => true  }, helper_method: 'index_filter'
    config.add_index_field 'biographical_t', label: 'Biographical Note', highlight: true, solr_params: { :"hl.alternateField" => "dd", :"hl.maxAlternateFieldLength" => 0, :"hl.highlightAlternate" => true  }, helper_method: 'index_filter'

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display
    config.add_show_field 'subtitle_t', label: 'Subtitle', highlight: true
    config.add_show_field 'series_t', label: 'Series', highlight: true, link_to_search: "series_facet", helper_method: 'highlightable_series_link'
    config.add_show_field 'subject_t', label: 'Topic', highlight: true, helper_method: :split_multiple
    config.add_show_field 'biographical_t', label: 'Biographical Note', highlight: true, helper_method: :split_multiple

app/views/catalog/_document_list.html.erb
<% # container for all documents in index list view -%>
<% view_config = local_assigns[:view_config] || blacklight_config&.view_config(document_index_view_type) %>
<div id="documents" class="documents-<%= view_config&.key || document_index_view_type %>">
  <% document_presenters = documents.map { |doc| document_presenter(doc) } -%>
  <%= render view_config.document_component.with_collection(document_presenters, partials: view_config.partials, counter_offset: @response&.start || 0) %>
</div>

app/views/catalog/_facet_pagination.html.erb
<%= render(Blacklight::FacetFieldPaginationComponent.new(facet_field: facet_field_presenter(@facet, @display_facet))) %>

app/views/catalog/_facet_pivot.html.erb
<%= render(Blacklight::FacetFieldListComponent.new(
      facet_field: facet_field_presenter(facet_field.merge(item_component: Blacklight::FacetItemPivotComponent), display_facet),
      layout: false)) %>

app/views/catalog/_group.html.erb
<% # container for all groups in index view -%>
<div id="groups">
  <%= render(Blacklight::Document::GroupComponent.with_collection(@response.groups, group_limit: @response.group_limit)) %>
</div>

app/views/catalog/_home.html.erb
<% #Search form can be added here, defaulted to the navbar for Bootstrap version -%>
<%= render :partial=>'home_text' %>

app/views/catalog/_index_default.html.erb
<% doc_presenter = index_presenter(document) %>
<%# default partial to display solr document fields in catalog index view -%>
<dl class="document-metadata dl-horizontal dl-invert">

  <% doc_presenter.fields_to_render.each do |field_name, field, field_presenter| -%>
    <% if should_render_index_field? document, field %>
	    <dt class="blacklight-<%= field_name.parameterize %>"><%= render_index_field_label document, field: field_name %></dt>
      <dd class="blacklight-<%= field_name.parameterize %>"><%= field_presenter.render %></dd>
    <% end -%>
  <% end -%>

</dl>

app/views/catalog/_index_header.html.erb
<%# OVERRIDE Blacklight 7.33.1 - add columns %>

<%# header bar for doc items in index view -%>
<div class="documentHeader row">
  <%# main title container for doc partial view
      How many bootstrap columns need to be reserved
      for bookmarks control depends on size.
  -%>
  <% document_actions = capture do %>
    <% # bookmark functions for items/docs -%>
    <%= render_index_doc_actions document, wrapping_class: "index-document-functions col-sm-3 col-lg-2" %>
  <% end %>
  <h3 class="index_title document-title-heading <%= document_actions.present? ? "col-sm-9 col-lg-10" : "col-md-12" %>">
    <% if counter = document_counter_with_offset(document_counter) %>
      <span class="document-counter">
        <%= t('blacklight.search.documents.counter', counter: counter) %>
      </span>
    <% end %>
    <%= link_to document['title_display'], solr_document_path(document, counter: counter, q: params[:q]) %>
  </h3>

  <%= document_actions %>
</div>

app/views/catalog/_paginate_compact.html.erb
<%= render Blacklight::Response::PaginationComponent.new(
  response: paginate_compact,
  theme: :blacklight_compact,
  page_entries_info: page_entries_info(paginate_compact),
  role: nil,
  html: { aria: {} })
%>

app/views/catalog/_search_header.html.erb
<%= render blacklight_config.view_config(document_index_view_type).search_header_component.new %>

app/views/catalog/_sort_and_per_page.html.erb
<div id="sortAndPerPage" class="sort-pagination d-md-flex justify-content-between" role="navigation" aria-label="<%= t('blacklight.search.per_page.aria_label')%>">
  <%= render partial: "paginate_compact", object: @response if show_pagination? %>
  <%= render_results_collection_tools wrapping_class: "search-widgets" %>
</div>
<%= render 'constraints' %>

app/views/catalog/_sort_widget.html.erb
<% if show_sort_and_per_page? %>
  <%= render(Blacklight::Response::SortComponent.new(
    choices: active_sort_fields.map { |key, config| [sort_field_label(config.key), key] },
    search_state: search_state,
    selected: current_sort_field&.key)) %>
<% end %>

app/views/catalog/email.html.erb
<%= render Blacklight::System::ModalComponent.new do |component| %>
  <% component.with_title { t('blacklight.email.form.title') } %>

  <% component.with_body do %>
    <%= render 'email_form' %>
  <% end %>
<% end %>

app/views/catalog/email_success.html.erb
<turbo-stream action="append" target="main-flashes">
  <template>
    <%= render '/shared/flash_msg' %>
  </template>
</turbo-stream>

app/views/catalog/sms_success.html.erb
<turbo-stream action="append" target="main-flashes">
  <template>
    <%= render '/shared/flash_msg' %>
  </template>
</turbo-stream>